# Generated by Django 3.0.8 on 2020-12-22 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentset',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Equipment.Character'),
        ),
        migrations.AddField(
            model_name='equipmentset',
            name='target_ip',
            field=models.IntegerField(default=0),
        ),
    ]
