# Generated by Django 3.0.8 on 2021-01-10 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_bonus', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='itemspec_item', to='Equipment.Item')),
            ],
        ),
        migrations.DeleteModel(
            name='ItemTypeSpec',
        ),
        migrations.AlterField(
            model_name='character',
            name='mastery',
            field=models.ManyToManyField(to='Equipment.ItemSpec'),
        ),
    ]
