# Generated by Django 3.0.8 on 2021-01-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0002_auto_20201222_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentset',
            name='target_ip',
        ),
        migrations.AddField(
            model_name='itemtier',
            name='target_ip',
            field=models.IntegerField(default=0, help_text='0 for cheapest, -1 for highest IP/Cost', verbose_name='Target IP'),
        ),
    ]
