# Generated by Django 3.0.8 on 2021-02-18 23:31

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0002_auto_20210110_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='EfficientItemResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_efficient_set', models.TextField()),
                ('equipment_set_name', models.CharField(max_length=100)),
                ('total_cost', models.IntegerField(default=0)),
                ('equpment_set_character', models.CharField(max_length=100)),
                ('time_saved', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='itemspec',
            options={'ordering': [django.db.models.expressions.F('item__item_name')]},
        ),
        migrations.AlterModelOptions(
            name='itemtier',
            options={'ordering': [django.db.models.expressions.F('item__item_name')]},
        ),
    ]
