# Generated by Django 3.0.8 on 2021-01-03 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0003_auto_20210102_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentset',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Equipment.Character'),
        ),
        migrations.AlterField(
            model_name='itemtier',
            name='target_ip',
            field=models.IntegerField(default=0, help_text='Positive for cheapest, negative for highest IP/Cost', verbose_name='Target IP'),
        ),
    ]
