# Generated by Django 3.0.8 on 2021-02-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0003_auto_20210218_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efficientitemresult',
            name='total_cost',
            field=models.CharField(max_length=50),
        ),
    ]
