# Generated by Django 3.0.8 on 2021-02-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0004_auto_20210218_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efficientitemresult',
            name='time_saved',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
