# Generated by Django 3.0.8 on 2021-02-19 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0005_auto_20210218_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='efficientitemresult',
            old_name='equpment_set_character',
            new_name='equipment_set_character',
        ),
    ]
