# Generated by Django 3.1.7 on 2021-12-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0007_market'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('tier', models.CharField(max_length=3)),
                ('quality', models.CharField(max_length=15)),
                ('price', models.CharField(max_length=50)),
                ('time_saved', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='mastery',
            field=models.ManyToManyField(blank=True, to='Equipment.ItemSpec'),
        ),
    ]
