# Generated by Django 3.1.7 on 2021-03-25 18:10

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Boot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boot_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mount_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BootSpeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField(default=0)),
                ('boot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bootspeed_boot', to='Item_Lists.boot')),
            ],
            options={
                'ordering': [django.db.models.expressions.F('boot__boot_name')],
            },
        ),
    ]
