# Generated by Django 3.1.7 on 2021-03-25 18:23

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('Item_Lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MountSpeedWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('mount', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bootspeed_boot', to='Item_Lists.mount')),
            ],
            options={
                'ordering': [django.db.models.expressions.F('mount__mount_name')],
            },
        ),
        migrations.CreateModel(
            name='BagWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bootspeed_boot', to='Item_Lists.bag')),
            ],
            options={
                'ordering': [django.db.models.expressions.F('bag__bag_name')],
            },
        ),
    ]
